// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPWVXSqhv6NRc6hvCN68s7iapVr8HH2Sw',
    appId: '1:168986426971:web:0bfbb2126b4a4aa12b497e',
    messagingSenderId: '168986426971',
    projectId: 'freebackend-616cd',
    authDomain: 'freebackend-616cd.firebaseapp.com',
    storageBucket: 'freebackend-616cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaDoV4SWdcdxCPR1XSGtuCzQRscWuyaO0',
    appId: '1:168986426971:android:006e3efa7addc4ab2b497e',
    messagingSenderId: '168986426971',
    projectId: 'freebackend-616cd',
    storageBucket: 'freebackend-616cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQJq1WHlQGaqPSvF-7EU1bpvzvby_u4Q',
    appId: '1:168986426971:ios:853324fab9837d7a2b497e',
    messagingSenderId: '168986426971',
    projectId: 'freebackend-616cd',
    storageBucket: 'freebackend-616cd.appspot.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAQJq1WHlQGaqPSvF-7EU1bpvzvby_u4Q',
    appId: '1:168986426971:ios:853324fab9837d7a2b497e',
    messagingSenderId: '168986426971',
    projectId: 'freebackend-616cd',
    storageBucket: 'freebackend-616cd.appspot.com',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPWVXSqhv6NRc6hvCN68s7iapVr8HH2Sw',
    appId: '1:168986426971:web:3325779ae2e52c6f2b497e',
    messagingSenderId: '168986426971',
    projectId: 'freebackend-616cd',
    authDomain: 'freebackend-616cd.firebaseapp.com',
    storageBucket: 'freebackend-616cd.appspot.com',
  );
}